Repository boozallen/sdp-libraries, pull requests merged in 2019-07, with the labels that each got.

#27 refactor to scm implementations
  github/README.rst
  github/github.groovy
  github/github_enterprise.groovy
  github/impls.groovy
  github/on_pull_request.groovy
Labels: documentation, enhancement

#38 GitHub library config
  github/library_config.groovy
Labels: enhancement

#37 adding library config for twistlock library
  twistlock/library_config.groovy
Labels: enhancement

#36 adding sonarqube library config
  sonarqube/library_config.groovy
Labels: enhancement

#29 Docker library configuration
  docker/library_config.groovy
Labels: enhancement

#30 adding a11y library config
  a11y/library_config.groovy
Labels: enhancement

#31 Openshift library config
  openshift/library_config.groovy
Labels: enhancement

#32 adding owasp_dep_check/library_config.groovy
  owasp_dep_check/library_config.groovy
Labels: enhancement

#33 Adding owasp_zap library config
  owasp_zap/library_config.groovy
Labels: enhancement

#34 adding protractory library config
  protractor/library_config.groovy
Labels: enhancement

#35 Sdp library config
  sdp/library_config.groovy
Labels: enhancement

#41 fixing typo in "SDP" library docs
  sdp/README.rst
Labels: documentation

#42 adding JTE plugin as dependency for Gradle tests
  build.gradle
  openshift/unit-tests/DeployToSpec.groovy
Labels: enhancement
