Repository boozallen/sdp-libraries, pull requests merged in 2020-04, with the labels that each got.

#72 Fixing typo in a11y library config
  a11y/library_config.groovy
Labels: bug

#76 Enhance Sysdig Secure Library
  docs/modules/ROOT/pages/libraries/sonarqube.adoc
  docs/modules/ROOT/pages/libraries/sysdig_secure.adoc
  libraries/sysdig_secure/library_config.groovy
  libraries/sysdig_secure/scan_container_image.groovy
Labels: enhancement

#77 add steps to SDP library to support JTE 1.7
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/libraries/sdp.adoc
  libraries/sdp/archive_pipeline_config.groovy
  libraries/sdp/create_workspace_stash.groovy
Labels: Breaking Change
