Repository boozallen/sdp-libraries, pull requests merged in 2022-07, with the labels that each got.

#153 Add Grype Scan library
  docs/styles/Vocab/SDP/accept.txt
  libraries/grype/README.md
  libraries/grype/library_config.groovy
  libraries/grype/resources/transform-grype-scan-results.sh
  libraries/grype/steps/container_image_scan.groovy
  libraries/grype/test/ContainerImageScanSpec.groovy
Labels: enhancement

#170 Grype library: add report_format/fail_on_severity defaults and fix bug where file extensions don't exist on generated reports
  libraries/grype/steps/container_image_scan.groovy
  libraries/grype/test/ContainerImageScanSpec.groovy
Labels: bug

#172 fixing Syft library file path issue
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: bug fix

#173 Syft filepath fix
  libraries/syft/steps/generate_sbom.groovy
Labels: bug fix

#174 Syft command fix
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: bug fix
