Repository boozallen/sdp-libraries, pull requests merged in 2022-06, with the labels that each got.

#158 Maven library replacement
  Justfile
  docs/styles/Microsoft/Terms.yml
  libraries/maven/README.md
  libraries/maven/library_config.groovy
  libraries/maven/steps/maven.groovy
  libraries/maven/steps/maven_invoke.groovy
  libraries/maven/test/MavenInvokeSpec.groovy
  libraries/maven/test/MavenTestSpec.groovy
  libraries/npm/README.md
Labels: enhancement, Breaking Change

#159 Adds .Net Library
  .gitignore
  libraries/dotnet/steps/dotnet_invoke.groovy
  libraries/dotnet/test/DotNetInvokeSpec.groovy
Labels: enhancement

#161 fixing typo in example config snippet
  libraries/owasp_dep_check/README.md
Labels: documentation

#162 Remove broken Maven library_config.groovy
  libraries/maven/library_config.groovy
Labels: bug

#163 fixing Maven required field check
  libraries/maven/steps/maven_invoke.groovy
Labels: bug

#164 fixing Maven config array handling
  libraries/maven/steps/maven_invoke.groovy
Labels: bug

#160 Added null safe operators and documentation for the .NET library
  libraries/dotnet/README.md
  libraries/dotnet/steps/dotnet_invoke.groovy
Labels: bug

#165 Enable suppression file support in OWASP dependency scan
  libraries/owasp_dep_check/README.md
  libraries/owasp_dep_check/steps/application_dependency_scan.groovy
  libraries/owasp_dep_check/test/ApplicationDependencySpec.groovy
Labels: enhancement, owasp-dep-check

#167 Support overriding the DotNet SDK SDP image used
  libraries/dotnet/README.md
  libraries/dotnet/steps/dotnet_invoke.groovy
Labels: enhancement
