Repository boozallen/sdp-libraries, pull requests merged in 2022-11, with the labels that each got.

#189 Syft multiple formats
  libraries/syft/README.md
  libraries/syft/library_config.groovy
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: enhancement

#191 Revert "Syft multiple formats"
  libraries/syft/README.md
  libraries/syft/library_config.groovy
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: skip-changelog

#192 Syft multiple SBOM formats
  libraries/syft/README.md
  libraries/syft/library_config.groovy
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: enhancement

#193 Grype SBOM scan capability
  libraries/grype/README.md
  libraries/grype/library_config.groovy
  libraries/grype/steps/container_image_scan.groovy
  libraries/grype/test/ContainerImageScanSpec.groovy
Labels: enhancement

#194 Add Cypress Testing Library
  libraries/cypress/README.md
  libraries/cypress/library_config.groovy
  libraries/cypress/steps/test_ui.groovy
  libraries/cypress/test/TestUISpec.groovy
Labels: enhancement

#195 Syft config removal option
  libraries/syft/README.md
  libraries/syft/library_config.groovy
  libraries/syft/steps/generate_sbom.groovy
Labels: bug fix

#196 Cypress test repo fix
  libraries/cypress/README.md
  libraries/cypress/library_config.groovy
  libraries/cypress/steps/end_to_end_test.groovy
  libraries/cypress/test/EndToEndTestSpec.groovy
Labels: Breaking Change, bug fix

#197 Cypress test repo subdirectory fix
  libraries/cypress/steps/end_to_end_test.groovy
Labels: bug fix

#198 Additional Cypress subdirectory fix
  libraries/cypress/steps/end_to_end_test.groovy
Labels: bug fix
