Repository boozallen/sdp-libraries, pull requests merged in 2022-08, with the labels that each got.

#177 Merging catalog-info.yaml file added to develop to main branch
  catalog-info.yaml
Labels: skip-changelog

#179 Update catalog-info.yaml to remove internal link
  catalog-info.yaml
Labels: skip-changelog

#178 Bug Fix: Syft Docker Save
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: bug

#182 Move catalog-info.yaml change from develop to main
  catalog-info.yaml
Labels: skip-changelog

#183 Bug Fix: Syft image retrieval
  libraries/syft/steps/generate_sbom.groovy
  libraries/syft/test/GenerateSBOMSpec.groovy
Labels: bug fix
